// SPDX-License-Identifier: AGPL-3.0-or-later
using Monitor.Simulation.Physiology;

namespace Monitor.Simulation.Authoring;

// Existing illustration IDs, retained for compatibility; not a wire protocol.
public static class AuthoredConductionSelection
{
    public static (int Atrial, int Conducted) Resolve(int index) => index switch
    {
        >= 0 and <= 3 => (index + 1, 1),
        4 or 16 or 18 => (3, 2),
        17 => (5, 4),
        5 or 6 or 19 or 20 or 21 => (4, 3),
        7 or 8 or 11 or 12 or 13 or 14 or 15 or 22 or 23 or 24 or 25 or 26 or 27 or 28 or 29 or 30 or 31 or 32 or 33 or 34 or 35 or 36 or 37 => (1, 1),
        9 or 39 => (2, 1),
        10 => (4, 1),
        38 => (3, 1),
        40 or 41 or 42 => (1, 1),
        _ => throw new ArgumentException("Invalid conduction selection."),
    };
    public static AvConductionPattern Pattern(int index) => index switch
    {
        42 => AvConductionPattern.SinusArrestIllustration,
        41 => AvConductionPattern.SinusArrhythmiaIllustration,
        39 => AvConductionPattern.VariableAtrialFlutterIllustration,
        6 => AvConductionPattern.WenckebachFourToThreeIllustration,
        7 => AvConductionPattern.CompleteAvBlockJunctionalIllustration,
        8 => AvConductionPattern.CompleteAvBlockVentricularIllustration,
        9 or 10 or 38 or 40 => AvConductionPattern.AtrialFlutterIllustration,
        11 => AvConductionPattern.AtrialFibrillationCoarseIllustration,
        12 => AvConductionPattern.AtrialFibrillationFineIllustration,
        13 => AvConductionPattern.VentricularFlutterIllustration,
        14 => AvConductionPattern.VentricularFibrillationCoarseIllustration,
        15 => AvConductionPattern.VentricularFibrillationFineIllustration,
        16 => AvConductionPattern.WenckebachThreeToTwoIllustration,
        17 => AvConductionPattern.WenckebachFiveToFourIllustration,
        18 => AvConductionPattern.MobitzTwoThreeToTwoIllustration,
        19 => AvConductionPattern.MobitzTwoFourToThreeIllustration,
        20 => AvConductionPattern.MobitzTwoRbbbFourToThreeIllustration,
        21 => AvConductionPattern.MobitzTwoLbbbFourToThreeIllustration,
        22 => AvConductionPattern.PrematureAtrialIllustration,
        23 => AvConductionPattern.BlockedPrematureAtrialIllustration,
        24 => AvConductionPattern.AberrantPrematureAtrialIllustration,
        25 => AvConductionPattern.PrematureJunctionalIllustration,
        26 => AvConductionPattern.PrematureJunctionalAfterQrsIllustration,
        27 => AvConductionPattern.PrematureJunctionalOverlappingIllustration,
        28 => AvConductionPattern.PrematureVentricularIllustration,
        29 => AvConductionPattern.VentricularBigeminyIllustration,
        30 => AvConductionPattern.VentricularTrigeminyIllustration,
        31 => AvConductionPattern.PolymorphicPvcIllustration,
        32 => AvConductionPattern.MultifocalPvcIllustration,
        33 => AvConductionPattern.InterpolatedPvcIllustration,
        34 => AvConductionPattern.VentricularCoupletIllustration,
        35 => AvConductionPattern.PolymorphicVentricularCoupletIllustration,
        36 => AvConductionPattern.RonTLongQtPvcIllustration,
        37 => AvConductionPattern.ShortCoupledRonTPvcIllustration,
        _ => AvConductionPattern.FixedPr,
    };
    public static int Index(int atrial, int conducted, AvConductionPattern pattern = AvConductionPattern.FixedPr) => (atrial, conducted, pattern) switch
    {
        ( >= 1 and <= 4, 1, AvConductionPattern.FixedPr) => atrial - 1,
        (3, 2, AvConductionPattern.FixedPr) => 4,
        (4, 3, AvConductionPattern.FixedPr) => 5,
        (4, 3, AvConductionPattern.WenckebachFourToThreeIllustration) => 6,
        (1, 1, AvConductionPattern.CompleteAvBlockJunctionalIllustration) => 7,
        (1, 1, AvConductionPattern.CompleteAvBlockVentricularIllustration) => 8,
        (1, 1, AvConductionPattern.SinusArrhythmiaIllustration) => 41,
        (1, 1, AvConductionPattern.SinusArrestIllustration) => 42,
        (1, 1, AvConductionPattern.AtrialFlutterIllustration) => 40,
        (2, 1, AvConductionPattern.AtrialFlutterIllustration) => 9,
        (4, 1, AvConductionPattern.AtrialFlutterIllustration) => 10,
        (3, 1, AvConductionPattern.AtrialFlutterIllustration) => 38,
        (2, 1, AvConductionPattern.VariableAtrialFlutterIllustration) => 39,
        (1, 1, AvConductionPattern.AtrialFibrillationCoarseIllustration) => 11,
        (1, 1, AvConductionPattern.AtrialFibrillationFineIllustration) => 12,
        (1, 1, AvConductionPattern.VentricularFlutterIllustration) => 13,
        (1, 1, AvConductionPattern.VentricularFibrillationCoarseIllustration) => 14,
        (1, 1, AvConductionPattern.VentricularFibrillationFineIllustration) => 15,
        (3, 2, AvConductionPattern.WenckebachThreeToTwoIllustration) => 16,
        (5, 4, AvConductionPattern.WenckebachFiveToFourIllustration) => 17,
        (3, 2, AvConductionPattern.MobitzTwoThreeToTwoIllustration) => 18,
        (4, 3, AvConductionPattern.MobitzTwoFourToThreeIllustration) => 19,
        (4, 3, AvConductionPattern.MobitzTwoRbbbFourToThreeIllustration) => 20,
        (4, 3, AvConductionPattern.MobitzTwoLbbbFourToThreeIllustration) => 21,
        (1, 1, AvConductionPattern.PrematureAtrialIllustration) => 22,
        (1, 1, AvConductionPattern.BlockedPrematureAtrialIllustration) => 23,
        (1, 1, AvConductionPattern.AberrantPrematureAtrialIllustration) => 24,
        (1, 1, AvConductionPattern.PrematureJunctionalIllustration) => 25,
        (1, 1, AvConductionPattern.PrematureJunctionalAfterQrsIllustration) => 26,
        (1, 1, AvConductionPattern.PrematureJunctionalOverlappingIllustration) => 27,
        (1, 1, AvConductionPattern.PrematureVentricularIllustration) => 28,
        (1, 1, AvConductionPattern.VentricularBigeminyIllustration) => 29,
        (1, 1, AvConductionPattern.VentricularTrigeminyIllustration) => 30,
        (1, 1, AvConductionPattern.PolymorphicPvcIllustration) => 31,
        (1, 1, AvConductionPattern.MultifocalPvcIllustration) => 32,
        (1, 1, AvConductionPattern.InterpolatedPvcIllustration) => 33,
        (1, 1, AvConductionPattern.VentricularCoupletIllustration) => 34,
        (1, 1, AvConductionPattern.PolymorphicVentricularCoupletIllustration) => 35,
        (1, 1, AvConductionPattern.RonTLongQtPvcIllustration) => 36,
        (1, 1, AvConductionPattern.ShortCoupledRonTPvcIllustration) => 37,
        _ => throw new ArgumentException("Invalid conduction selection."),
    };
}
