# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate deterministic reference facts and independent numerical fixtures.

No network or import-time work. Optionally verify the original ERS workbook
against the recorded hash and the transcribed adult FRC M-spline subset.
"""
import argparse
from decimal import Decimal
import hashlib
import json
import math
from pathlib import Path
from xml.etree import ElementTree
from zipfile import ZipFile


ROOT = Path(__file__).resolve().parents[1]


def verify_workbook(path, reference):
    if hashlib.sha256(path.read_bytes()).hexdigest() != reference['frc']['workbook_sha256']:
        raise ValueError('GLI workbook hash mismatch')
    ns = {'s': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
    with ZipFile(path) as workbook:
        for number, sex in [(1, 'male'), (2, 'female')]:
            rows = ElementTree.fromstring(workbook.read(f'xl/worksheets/sheet{number}.xml'))
            pairs = []
            for row in rows.findall('s:sheetData/s:row', ns)[1:]:
                cells = {cell.attrib['r'][0]: cell.find('s:v', ns).text for cell in row}
                if Decimal(cells['A']) >= 18:
                    pairs.append((Decimal(cells['A']), Decimal(cells['B'])))
            expected = [(Decimal(18) + Decimal('.25') * index, Decimal(value))
                        for index, value in enumerate(reference['frc']['mspline'][sex])]
            if pairs != expected:
                raise ValueError(f'GLI {sex} adult M-spline transcription mismatch')


def generate(reference):
    lines = ['// SPDX-License-Identifier: AGPL-3.0-or-later',
             '// Generated by tools/generate_oxygenation_defaults.py; numerical facts, not upstream code.',
             '// Provenance: eng/physiology/oxygenation-defaults.json. Do not edit by hand.',
             'namespace Monitor.Simulation.Physiology;', '',
             'internal static class OxygenationReferenceData', '{']
    for label, section in [('Set', None), ('Frc', 'frc'), ('Hemoglobin', 'hemoglobin'),
                           ('BasalMetabolism', 'basal_metabolism'), ('BloodVolume', 'blood_volume')]:
        value = reference['model_id'] if section is None else reference[section]['model_id']
        lines.append(f'    internal const string {label}Id = "{value}";')
    for sex in ['male', 'female']:
        groups = {'FrcSpline': reference['frc']['mspline'][sex],
                  'FrcCoefficients': reference['frc'][sex + '_coefficients'],
                  'HemoglobinMeans': reference['hemoglobin'][sex + '_means'],
                  'BasalCoefficients': sum(reference['basal_metabolism'][sex + '_coefficients'], []),
                  'BloodCoefficients': reference['blood_volume'][sex + '_coefficients']}
        for suffix, values in groups.items():
            name = sex.title() + suffix
            lines.extend([f'    private static readonly decimal[] {name}Data =', '    ['])
            for start in range(0, len(values), 4):
                values_line = ', '.join(format(Decimal(v), 'f') + 'm' for v in values[start:start + 4])
                lines.append('        ' + values_line + ',')
            lines.extend(['    ];', f'    internal static ReadOnlySpan<decimal> {name} => {name}Data;'])
    lines.extend(['}', ''])
    return '\n'.join(lines)


def validation_vectors(reference):
    rows = []
    for sex in ['male', 'female']:
        intercept, age_log, height_log = map(float, reference['frc'][sex + '_coefficients'])
        spline = list(map(float, reference['frc']['mspline'][sex]))
        for age in [18, 20, 25.125, 29.99, 30, 35, 59.99, 60, 69.5, 79.99, 80]:
            index = math.floor((age - 18) * 4)
            fraction = (age - 18) * 4 - index
            age_spline = spline[index] if fraction == 0 else spline[index] + fraction * (spline[index + 1] - spline[index])
            for height in [140, 165, 175, 190, 210]:
                value = math.exp(intercept + age_log * math.log(age) + height_log * math.log(height) + age_spline) * 1000
                rows.append({'Sex': sex, 'AgeYears': age, 'HeightCm': height, 'FrcMlBtps': round(value, 9)})
    return json.dumps({'ReferenceSetId': reference['model_id'], 'Frc': rows}, indent=2) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--verify-workbook', type=Path)
    args = parser.parse_args()
    reference = json.loads((ROOT / 'eng/physiology/oxygenation-defaults.json').read_text(encoding='utf-8'))
    if args.verify_workbook:
        verify_workbook(args.verify_workbook, reference)
    outputs = {
        ROOT / 'src/Monitor.Simulation/Physiology/OxygenationReferenceData.g.cs': generate(reference),
        ROOT / 'eng/physiology/oxygenation-defaults-validation.json': validation_vectors(reference),
    }
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                raise ValueError(f'Generated output differs: {path}')
        else:
            path.write_text(content, encoding='utf-8')
    print('PASS: oxygenation reference generation, 110 independent FRC vectors' +
          (' and original GLI workbook' if args.verify_workbook else ''))


if __name__ == '__main__':
    main()
