#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Render the application icon from its SVG masters into PNG and multi-size ICO.

app-icon.svg is the master for 48 px and larger; app-icon-small.svg drops the
glow and thickens strokes so 32 px and smaller stay legible. Rendering uses
ImageMagick with its librsvg coder. Output is reproducible for one toolchain;
--check compares regenerated bytes with the committed files.
"""
import argparse
from pathlib import Path
import shutil
import struct
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / 'src/Monitor.Desktop/Assets'
ICO_SIZES = (16, 20, 24, 32, 40, 48, 64, 128, 256)
SMALL_MAXIMUM = 32
PREVIEW_SIZE = 512


def render(svg, size, scratch):
    """Render the SVG at exactly size x size pixels with deterministic PNG metadata."""
    source = (ASSETS / svg).read_text(encoding='utf-8')
    sized = source.replace('width="1024" height="1024"', f'width="{size}" height="{size}"', 1)
    if sized == source:
        raise ValueError(f'{svg} must declare width="1024" height="1024"')
    template = Path(scratch) / f'{size}-{svg}'
    template.write_text(sized, encoding='utf-8')
    output = Path(scratch) / f'{size}-{svg}.png'
    subprocess.run(['magick', '-background', 'none', f'RSVG:{template}', '-strip',
                    '-define', 'png:exclude-chunks=date,time', f'PNG32:{output}'], check=True)
    return output.read_bytes()


def icon_container(images):
    """Pack PNG images into an ICO directory; 256 px is stored as width/height 0."""
    header = struct.pack('<HHH', 0, 1, len(images))
    offset = len(header) + 16 * len(images)
    entries = b''
    payload = b''
    for size, data in images:
        side = 0 if size == 256 else size
        entries += struct.pack('<BBBBHHII', side, side, 0, 0, 1, 32, len(data), offset + len(payload))
        payload += data
    return header + entries + payload


def build(scratch):
    images = [(size, render('app-icon-small.svg' if size <= SMALL_MAXIMUM else 'app-icon.svg', size, scratch))
              for size in ICO_SIZES]
    return {
        'app-icon.ico': icon_container(images),
        'app-icon.png': render('app-icon.svg', PREVIEW_SIZE, scratch),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Compare with committed outputs without writing')
    args = parser.parse_args()
    if shutil.which('magick') is None:
        parser.error('ImageMagick 7 with the librsvg coder is required')
    with tempfile.TemporaryDirectory(prefix='app-icon-') as scratch:
        outputs = build(scratch)
    stale = [name for name, data in outputs.items()
             if not (ASSETS / name).is_file() or (ASSETS / name).read_bytes() != data]
    if args.check:
        for name in stale:
            print(f'stale: {name}', file=sys.stderr)
        return 1 if stale else 0
    for name, data in outputs.items():
        (ASSETS / name).write_bytes(data)
        print(f'wrote {(ASSETS / name).relative_to(ROOT)} ({len(data)} bytes)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
