#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Author textbook-constrained ECG and synthetic Resp tables offline; --check verifies exact generated bytes."""
import argparse
import hashlib
import json
from fractions import Fraction
from pathlib import Path
import struct
from spdx_headers import with_header


def sample_shape(shape):
    values = []
    for (start, first), (end, last) in zip(shape['landmarks'], shape['landmarks'][1:]):
        for index in range(start, end):
            t = Fraction(index - start, end - start)
            values.append(round((first + (last - first) * (3 * t * t - 2 * t * t * t)) * (1 << 32)))
    if len(values) != shape['length']:
        raise ValueError('landmarks must span the declared table length')
    return values


def electrode_shapes(manifest, reference):
    original = sample_shape(reference['tables']['Qrs'])
    limbs = [[round(Fraction(value * weight, 1000)) for value in original]
             for weight in manifest['limb_qrs_weights_per_1000']]
    phases = [sample_shape({'length': manifest['phase_length'], 'landmarks': manifest['phase_landmarks'][name]})
              for name in ['Early', 'Main', 'Terminal']]
    values = list(limbs)
    for weights in manifest['chest_component_microvolts']:
        values.append([round(Fraction(limbs[0][i] + limbs[1][i] + limbs[3][i], 3) +
                             sum(weight * phase[i] for weight, phase in zip(weights, phases)))
                       for i in range(manifest['phase_length'])])
    return {name: {'values_q32': value} for name, value in zip(
        ['RA', 'LA', 'RL', 'LL', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6'], values)}


def render(namespace, class_name, shapes, timing=None):
    lines = ['// Generated by tools/generate_demo_morphology.py; do not edit.',
             '// Project-authored reference illustration; not a validated physiological preset.',
             f'namespace {namespace};', '', f'internal static class {class_name}', '{']
    if timing is not None:
        values = [timing[key] * 1_000_000 for key in ['rr', 'p', 'pr', 'qrs', 'qt', 't']]
        lines.append('    internal static EcgCycleTiming Timing { get; } = new(' + ', '.join(map(str, values)) + ');')
    for name, shape in shapes.items():
        values = shape.get('values_q32')
        if values is None:
            values = sample_shape(shape)
        digest = hashlib.sha256(b''.join(struct.pack('<q', value) for value in values)).hexdigest()
        lines += [f'    // Q32 little-endian table SHA-256: {digest}',
                  f'    internal static IReadOnlyList<long> {name} {{ get; }} = Array.AsReadOnly(new long[]', '    {']
        for offset in range(0, len(values), 4):
            lines.append('        ' + ', '.join(str(value) for value in values[offset:offset + 4]) + ',')
        lines += ['    });']
    lines += ['}', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    manifest = json.loads((root / 'eng/physiology/textbook-ecg-reference.json').read_text())
    chest = json.loads((root / 'eng/physiology/textbook-chest-progression.json').read_text())
    outputs = {
        root / 'src/Monitor.Simulation/Physiology/TextbookElectrodeQrsTables.cs': render(
            'Monitor.Simulation.Physiology', 'TextbookElectrodeQrsTables', electrode_shapes(chest, manifest)),
        root / 'src/Monitor.Simulation/Physiology/TextbookEcgTables.cs': render(
            'Monitor.Simulation.Physiology', 'TextbookEcgTables', manifest['tables'], manifest['timing_ms']),
        root / 'src/Monitor.Desktop/PhysiologyDemoTables.cs': render(
            'Monitor.Desktop', 'PhysiologyDemoTables',
            {'Resp': {'length': 64, 'landmarks': [[0, 0], [32, 1000], [64, 0]]}}),
    }
    for target, expected in outputs.items():
        expected = with_header(target.name, expected.encode()).decode()
        if args.check:
            if target.read_text() != expected:
                raise SystemExit(f'Morphology differs from reproducible output: {target.name}')
        else:
            target.write_text(expected)
    if args.check:
        print('ok: textbook ECG and synthetic Resp Q32 tables match offline authoring')


if __name__ == '__main__':
    main()
