#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Author physiological illustration tables offline; --check verifies exact generated bytes."""
import argparse
import hashlib
import json
from fractions import Fraction
from pathlib import Path
import struct
from spdx_headers import with_header


def sample_shape(shape):
    if 'polynomial_coefficients' in shape:
        coefficients = shape['polynomial_coefficients']
        return [round(sum(Fraction(coefficient) * Fraction(index, shape['length']) ** power
                          for power, coefficient in enumerate(coefficients)) * (1 << 32))
                for index in range(shape['length'])]
    values = []
    for (start, first), (end, last) in zip(shape['landmarks'], shape['landmarks'][1:]):
        for index in range(start, end):
            t = Fraction(index - start, end - start)
            values.append(round((first + (last - first) * (3 * t * t - 2 * t * t * t)) * (1 << 32)))
    if len(values) != shape['length']:
        raise ValueError('landmarks must span the declared table length')
    return values


def electrode_shapes(manifest, reference):
    original = sample_shape(reference['tables']['Qrs'])
    limbs = [[round(Fraction(value * weight, 1000)) for value in original]
             for weight in manifest['limb_qrs_weights_per_1000']]
    phases = [sample_shape({'length': manifest['phase_length'], 'landmarks': manifest['phase_landmarks'][name]})
              for name in ['Early', 'Main', 'Terminal']]
    values = list(limbs)
    for weights in manifest['chest_component_microvolts']:
        values.append([round(Fraction(limbs[0][i] + limbs[1][i] + limbs[3][i], 3) +
                             sum(weight * phase[i] for weight, phase in zip(weights, phases)))
                       for i in range(manifest['phase_length'])])
    shapes = {name: {'values_q32': value} for name, value in zip(
        ['RA', 'LA', 'RL', 'LL', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6'], values)}
    for column, name in enumerate(['PWeightsQ32', 'TWeightsQ32']):
        shapes[name] = {'values_q32': [row[column] * (1 << 32)
                                     for row in manifest['p_t_electrode_weights_per_1000']]}
    return shapes


def hyperkalemia_qrs_shapes(manifest, chest, reference):
    # Re-author the continuous components, not sign-wise gain on sampled ECG.
    # Fraction arithmetic keeps the offline table deterministic.
    r = Fraction(manifest['r_gain_permille'], 1000)
    terminal = Fraction(manifest['s_gain_permille'], 1000)
    landmarks = reference['tables']['Qrs']['landmarks']
    modified_reference = {**reference, 'tables': {**reference['tables'], 'Qrs': {
        **reference['tables']['Qrs'], 'landmarks': [
            [phase, amplitude * (r if phase == 56 else terminal if phase == 88 else 1)]
            for phase, amplitude in landmarks]}}}
    modified_chest = {**chest, 'chest_component_microvolts': [
        [q, main * r, s * terminal] for q, main, s in chest['chest_component_microvolts']]}
    shapes = electrode_shapes(modified_chest, modified_reference)
    return {name: shape for name, shape in shapes.items() if name not in ('PWeightsQ32', 'TWeightsQ32')}


def ventricular_shapes(manifest, chest):
    phases = [sample_shape({'length': chest['phase_length'], 'landmarks': chest['phase_landmarks'][name]})
              for name in ['Early', 'Main', 'Terminal']]
    leads = {name: [sum(weight * phase[i] for weight, phase in zip(weights, phases))
                    for i in range(chest['phase_length'])]
             for name, weights in manifest['authored_choices']['leadComponentsMicrovolts'].items()}
    ra = [round(Fraction(-i - ii, 3)) for i, ii in zip(leads['I'], leads['II'])]
    la = [r + i for r, i in zip(ra, leads['I'])]
    ll = [r + ii for r, ii in zip(ra, leads['II'])]
    wilson = [round(Fraction(r + l + f, 3)) for r, l, f in zip(ra, la, ll)]
    values = [ra, la, [0] * chest['phase_length'], ll]
    values += [[v + w for v, w in zip(leads[f'V{i}'], wilson)] for i in range(1, 7)]
    return {name: {'values_q32': value} for name, value in zip(
        ['RA', 'LA', 'RL', 'LL', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6'], values)}



def conduction_shapes(manifest):
    authored = manifest['authored_choices']
    leads = {name: sample_shape(shape) for name, shape in authored['leadQrsShapes'].items()}
    def electrodes(values):
        ra = [round(Fraction(-i - ii, 3)) for i, ii in zip(values['I'], values['II'])]
        la = [r + i for r, i in zip(ra, values['I'])]
        ll = [r + ii for r, ii in zip(ra, values['II'])]
        wilson = [round(Fraction(r + l + f, 3)) for r, l, f in zip(ra, la, ll)]
        return [ra, la, [0] * len(ra), ll] + [
            [v + w for v, w in zip(values[f'V{i}'], wilson)] for i in range(1, 7)]
    shapes = {name: {'values_q32': values} for name, values in zip(
        ['RA', 'LA', 'RL', 'LL', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6'], electrodes(leads))}
    t = electrodes({name: [amplitude * (1 << 32)] for name, amplitude in authored['leadTMicrovolts'].items()})
    shapes['TAmplitudesQ32'] = {'values_q32': [value[0] for value in t]}
    return shapes



def fibrillation_shapes(manifest):
    authored = manifest['authored_choices']
    state = authored['offlineSeed']
    def next_value():
        nonlocal state
        state = (1664525 * state + 1013904223) & 0xffffffff
        return state
    values = []
    while len(values) < authored['tileLength']:
        remaining = authored['tileLength'] - len(values)
        if remaining <= 42:
            width = remaining
        else:
            choices = [width for width in range(25, 43) if remaining - width >= 25 and not 43 <= remaining - width <= 49]
            width = choices[next_value() % len(choices)]
        if not 25 <= width <= 42:
            raise ValueError('f cycle outside authored frequency bounds')
        amplitude = 80 + next_value() % 141
        first = width * (22 + next_value() % 17) // 100
        second = width * (62 + next_value() % 17) // 100
        negative = -(amplitude * (50 + next_value() % 71) // 100)
        values += sample_shape({'length': width, 'landmarks': [[0, 0], [first, amplitude], [second, negative], [width, 0]]})
    return {'Cycle': {'values_q32': values}, 'WeightsQ32': {'values_q32': [weight * (1 << 32) for weight in authored['electrodeWeightsPer1000']]}}



def ventricular_disorganization_shapes(manifest):
    authored = manifest['authored_choices']
    state = authored['vfSeed']
    def next_value():
        nonlocal state
        state = (1664525 * state + 1013904223) & 0xffffffff
        return state
    minimum, maximum = authored['vfCycleSamples']
    low, high = authored['vfPeakMicrovolts']
    values = []
    while len(values) < authored['vfTileLength']:
        remaining = authored['vfTileLength'] - len(values)
        width = remaining if remaining <= maximum else minimum + next_value() % (min(maximum, remaining - minimum) - minimum + 1)
        if not minimum <= width <= maximum:
            raise ValueError('VF cycle outside authoring bounds')
        amplitude = low + next_value() % (high - low + 1)
        first = width * (20 + next_value() % 21) // 100
        second = width * (60 + next_value() % 21) // 100
        negative = -(amplitude * (50 + next_value() % 71) // 100)
        values += sample_shape({'length': width, 'landmarks': [[0, 0], [first, amplitude], [second, negative], [width, 0]]})
    return {'Flutter': authored['flutterShape'], 'Fibrillation': {'values_q32': values},
            'WeightsQ32': {'values_q32': [weight * (1 << 32) for weight in authored['electrodeWeightsPer1000']]}}


def render(namespace, class_name, shapes, timing=None):
    lines = ['// Generated by tools/generate_demo_morphology.py; do not edit.',
             '// Project-authored reference illustration; not a validated physiological preset.',
             f'namespace {namespace};', '', f'internal static class {class_name}', '{']
    if timing is not None:
        values = [timing[key] * 1_000_000 for key in ['rr', 'p', 'pr', 'qrs', 'qt', 't']]
        lines.append('    internal static EcgCycleTiming Timing { get; } = new(' + ', '.join(map(str, values)) + ');')
    for name, shape in shapes.items():
        values = shape.get('values_q32')
        if values is None:
            values = sample_shape(shape)
        digest = hashlib.sha256(b''.join(struct.pack('<q', value) for value in values)).hexdigest()
        lines += [f'    // Q32 little-endian table SHA-256: {digest}',
                  f'    internal static IReadOnlyList<long> {name} {{ get; }} = Array.AsReadOnly(new long[]', '    {']
        for offset in range(0, len(values), 4):
            lines.append('        ' + ', '.join(str(value) for value in values[offset:offset + 4]) + ',')
        lines += ['    });']
    lines += ['}', '']
    return '\n'.join(lines)


def arterial_shape(manifest):
    digest = hashlib.sha256(json.dumps(manifest['upstream_vertices'], separators=(',', ':')).encode()).hexdigest()
    if digest != manifest['upstream_vertices_sha256']:
        raise ValueError('upstream pressure vertex evidence changed')
    vertices = [Fraction(value) for value in manifest['upstream_vertices']]
    for index, value in manifest['modified_vertices'].items():
        vertices[int(index)] = Fraction(value)
    values = []
    for sample in range(manifest['length']):
        position = Fraction(sample * (len(vertices) - 1), manifest['length'])
        index = int(position)
        value = vertices[index] + (vertices[index + 1] - vertices[index]) * (position - index)
        values.append(round(value / Fraction(manifest['normalization_peak']) * (1 << 32)))
    return {'Pulse': {'values_q32': values}}


def capnogram_shape(manifest):
    digest = hashlib.sha256(json.dumps(manifest['upstream_vertices'], separators=(',', ':')).encode()).hexdigest()
    if digest != manifest['upstream_vertices_sha256']:
        raise ValueError('upstream CO2 vertex evidence changed')
    v = [Fraction(value) for value in manifest['upstream_vertices']]
    values = [0] * 32
    for vertices, length in [([Fraction(0)] + v[:15], 64), (v[14:213], 384), (v[212:], 32)]:
        for sample in range(length):
            position = Fraction(sample * (len(vertices) - 1), length)
            index = int(position)
            value = vertices[index] + (vertices[index + 1] - vertices[index]) * (position - index)
            values.append(round(value / Fraction('0.7') * (1 << 32)))
    return {'Cycle': {'values_q32': values}}


def cvp_shapes(manifest):
    seeds = manifest['upstream_seeds']
    if hashlib.sha256(json.dumps(seeds, sort_keys=True, separators=(',', ':')).encode()).hexdigest() != manifest['upstream_seeds_sha256']:
        raise ValueError('upstream CVP vertex evidence changed')
    atrial = [Fraction(value) for value in seeds['CVP_Atrioventricular'][:44]]
    first, last = atrial[0], atrial[-1]
    atrial = [max(Fraction(0), value - first - (last - first) * Fraction(index, 43)) for index, value in enumerate(atrial)]
    ventricular = [Fraction(value) for value in seeds['CVP_Ventricular'][36:87]]
    shapes = dict(manifest['project_tables'])
    for name, vertices in [('A', atrial), ('V', ventricular)]:
        peak = max(vertices)
        values = []
        for sample in range(128):
            position = Fraction(sample * (len(vertices) - 1), 128)
            index = int(position)
            value = vertices[index] + (vertices[index + 1] - vertices[index]) * (position - index)
            values.append(round(value / peak * (1 << 32)))
        shapes[name] = {'values_q32': values}
    return shapes


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    manifest = json.loads((root / 'eng/physiology/textbook-ecg-reference.json').read_text())
    chest = json.loads((root / 'eng/physiology/textbook-chest-progression.json').read_text())
    high_k_qrs = json.loads((root / 'eng/physiology/hyperkalemia-qrs-voltage.json').read_text())
    pleth = json.loads((root / 'eng/physiology/pleth-pulse-reference.json').read_text(), parse_float=Fraction)
    arterial = json.loads((root / 'eng/physiology/infirmary-arterial-pulse.json').read_text())
    capnogram = json.loads((root / 'eng/physiology/infirmary-capnogram.json').read_text())
    pulmonary = json.loads((root / 'eng/physiology/infirmary-pulmonary-artery.json').read_text())
    cvp = json.loads((root / 'eng/physiology/infirmary-cvp-components.json').read_text())
    if hashlib.sha256((root / cvp['license_file']).read_bytes()).hexdigest() != cvp['license_sha256']:
        raise ValueError('upstream CVP license evidence changed')
    if hashlib.sha256((root / pulmonary['license_file']).read_bytes()).hexdigest() != pulmonary['license_sha256']:
        raise ValueError('upstream PA license evidence changed')
    if hashlib.sha256((root / capnogram['license_file']).read_bytes()).hexdigest() != capnogram['license_sha256']:
        raise ValueError('upstream CO2 license evidence changed')
    if hashlib.sha256((root / arterial['license_file']).read_bytes()).hexdigest() != arterial['license_sha256']:
        raise ValueError('upstream ABP license evidence changed')
    st = json.loads((root / 'eng/physiology/st-segment-illustration.json').read_text())
    infarction = json.loads((root / 'eng/physiology/infarction-illustration.json').read_text())
    right_ventricular = json.loads((root / 'eng/physiology/right-ventricular-illustration.json').read_text())
    biventricular = json.loads((root / 'eng/physiology/biventricular-illustration.json').read_text())
    severe_right = json.loads((root / 'eng/physiology/severe-right-ventricular-illustration.json').read_text())
    pulmonary_heart = json.loads((root / 'eng/physiology/pulmonary-heart-illustration.json').read_text())
    t_contour = json.loads((root / 'eng/physiology/t-contour-illustration.json').read_text())
    escape = json.loads((root / 'eng/physiology/complete-avb-ventricular-illustration.json').read_text())
    flutter = json.loads((root / 'eng/physiology/atrial-flutter-illustration.json').read_text())
    flutter_shapes = dict(flutter['tables'])
    flutter_shapes['AmplitudesQ32'] = {'values_q32': [value * (1 << 32) for value in flutter['authored_choices']['electrodeAmplitudesMicrovolts']]}
    fibrillation = json.loads((root / 'eng/physiology/atrial-fibrillation-illustration.json').read_text())
    ventricular_disorganization = json.loads((root / 'eng/physiology/ventricular-disorganization-illustration.json').read_text())
    rbbb = json.loads((root / 'eng/physiology/right-bundle-block-illustration.json').read_text())
    lbbb = json.loads((root / 'eng/physiology/left-bundle-block-illustration.json').read_text())
    outputs = {
        root / 'src/Monitor.Simulation/Physiology/LeftBundleBlockTables.cs': render(
            'Monitor.Simulation.Physiology', 'LeftBundleBlockTables', conduction_shapes(lbbb)),
        root / 'src/Monitor.Simulation/Physiology/RightBundleBlockTables.cs': render(
            'Monitor.Simulation.Physiology', 'RightBundleBlockTables', conduction_shapes(rbbb)),
        root / 'src/Monitor.Simulation/Physiology/VentricularDisorganizationTables.cs': render(
            'Monitor.Simulation.Physiology', 'VentricularDisorganizationTables', ventricular_disorganization_shapes(ventricular_disorganization)),
        root / 'src/Monitor.Simulation/Physiology/AtrialFibrillationTables.cs': render(
            'Monitor.Simulation.Physiology', 'AtrialFibrillationTables', fibrillation_shapes(fibrillation)),
        root / 'src/Monitor.Simulation/Physiology/AtrialFlutterTables.cs': render(
            'Monitor.Simulation.Physiology', 'AtrialFlutterTables', flutter_shapes),
        root / 'src/Monitor.Simulation/Physiology/VentricularEscapeTables.cs': render(
            'Monitor.Simulation.Physiology', 'VentricularEscapeTables', conduction_shapes(escape)),
        root / 'src/Monitor.Simulation/Physiology/TContourTables.cs': render(
            'Monitor.Simulation.Physiology', 'TContourTables', t_contour['tables']),
        root / 'src/Monitor.Simulation/Physiology/SevereRightVentricularQrsTables.cs': render(
            'Monitor.Simulation.Physiology', 'SevereRightVentricularQrsTables', ventricular_shapes(severe_right, chest)),
        root / 'src/Monitor.Simulation/Physiology/PulmonaryHeartQrsTables.cs': render(
            'Monitor.Simulation.Physiology', 'PulmonaryHeartQrsTables', ventricular_shapes(pulmonary_heart, chest)),
        root / 'src/Monitor.Simulation/Physiology/BiventricularQrsTables.cs': render(
            'Monitor.Simulation.Physiology', 'BiventricularQrsTables', ventricular_shapes(biventricular, chest)),
        root / 'src/Monitor.Simulation/Physiology/RightVentricularQrsTables.cs': render(
            'Monitor.Simulation.Physiology', 'RightVentricularQrsTables', ventricular_shapes(right_ventricular, chest)),
        root / 'src/Monitor.Simulation/Physiology/InfarctionIllustrationTables.cs': render(
            'Monitor.Simulation.Physiology', 'InfarctionIllustrationTables', infarction['tables']),
        root / 'src/Monitor.Simulation/Physiology/StSegmentTables.cs': render(
            'Monitor.Simulation.Physiology', 'StSegmentTables', st['tables']),
        root / 'src/Monitor.Simulation/Physiology/CvpComponentTables.cs':
            '// A/V adapted from Infirmary Integrated CVP seeds, Ibi Keller (Tanjera); C/X/Y/Resp are project-authored.\n'
            '// Apache-2.0; see eng/licenses/infirmary-integrated-LICENSE.md and docs/infirmary-source-notice.md.\n' + render(
                'Monitor.Simulation.Physiology', 'CvpComponentTables', cvp_shapes(cvp)).replace(
                    'Project-authored reference illustration', 'Mixed adapted/project-authored reference illustration'),
        root / 'src/Monitor.Simulation/Physiology/PulmonaryArteryTables.cs':
            '// Adapted from Infirmary Integrated PA_Default, Ibi Keller (Tanjera).\n'
            '// Apache-2.0; see eng/licenses/infirmary-integrated-LICENSE.md and docs/infirmary-source-notice.md.\n' + render(
                'Monitor.Simulation.Physiology', 'PulmonaryArteryTables', arterial_shape(pulmonary)).replace(
                    'Project-authored reference illustration', 'Adapted upstream reference illustration'),
        root / 'src/Monitor.Simulation/Physiology/CapnogramTables.cs':
            '// Adapted from Infirmary Integrated ETCO2_Default, Ibi Keller (Tanjera).\n'
            '// Apache-2.0; see eng/licenses/infirmary-integrated-LICENSE.md and docs/infirmary-source-notice.md.\n' + render(
                'Monitor.Simulation.Physiology', 'CapnogramTables', capnogram_shape(capnogram)).replace(
                    'Project-authored reference illustration', 'Adapted upstream reference illustration'),
        root / 'src/Monitor.Simulation/Physiology/ArterialPulseTables.cs':
            '// Adapted from Infirmary Integrated ABP_Default, Ibi Keller (Tanjera).\n'
            '// Apache-2.0; see eng/licenses/infirmary-integrated-LICENSE.md and docs/infirmary-source-notice.md.\n' + render(
                'Monitor.Simulation.Physiology', 'ArterialPulseTables', arterial_shape(arterial)).replace(
                    'Project-authored reference illustration', 'Adapted upstream reference illustration'),
        root / 'src/Monitor.Simulation/Physiology/PlethPulseTables.cs': render(
            'Monitor.Simulation.Physiology', 'PlethPulseTables', pleth['tables']),
        root / 'src/Monitor.Simulation/Physiology/HyperkalemiaQrsTables.cs': render(
            'Monitor.Simulation.Physiology', 'HyperkalemiaQrsTables', hyperkalemia_qrs_shapes(high_k_qrs, chest, manifest)),
        root / 'src/Monitor.Simulation/Physiology/TextbookElectrodeQrsTables.cs': render(
            'Monitor.Simulation.Physiology', 'TextbookElectrodeQrsTables', electrode_shapes(chest, manifest)),
        root / 'src/Monitor.Simulation/Physiology/TextbookEcgTables.cs': render(
            'Monitor.Simulation.Physiology', 'TextbookEcgTables', manifest['tables'], manifest['timing_ms']),
        root / 'src/Monitor.Simulation/Physiology/RespirationTables.cs': render(
            'Monitor.Simulation.Physiology', 'RespirationTables',
            {'Cycle': {'length': 64, 'landmarks': [[0, 0], [32, 1], [64, 0]]}}),
    }
    for target, expected in outputs.items():
        expected = with_header(target.name, expected.encode()).decode()
        if args.check:
            if target.read_text() != expected:
                raise SystemExit(f'Morphology differs from reproducible output: {target.name}')
        else:
            target.write_text(expected)
    if args.check:
        print('ok: ECG/ST, Resp, Pleth, ABP, CO2, PA and CVP Q32 tables match offline authoring')


if __name__ == '__main__':
    main()
