#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate the project's original quarter-sine table using Decimal math."""
import argparse
from decimal import Decimal, localcontext
from pathlib import Path


def generate():
    with localcontext() as context:
        context.prec = 90
        pi = Decimal('3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628')
        values = []
        for index in range(257):
            x = pi * index / 512
            term = total = x
            for n in range(1, 80):
                term *= -x * x / ((2 * n) * (2 * n + 1))
                total += term
            values.append(int((total * 2147483647).to_integral_value()))
    lines = ['// SPDX-License-Identifier: AGPL-3.0-or-later',
             '// Generated by tools/generate_audio_tables.py; original mathematical table.',
             'namespace Monitor.Infrastructure.Audio;', '',
             'internal static class SineTable', '{',
             '    internal static ReadOnlySpan<int> Quarter => Values;',
             '    private static readonly int[] Values =', '    [']
    for offset in range(0, len(values), 8):
        lines.append('        ' + ', '.join(str(v) for v in values[offset:offset + 8]) + ',')
    return '\n'.join(lines + ['    ];', '}', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = Path(__file__).resolve().parents[1] / 'src/Monitor.Infrastructure/Audio/SineTable.cs'
    expected = generate()
    if args.check:
        if path.read_text() != expected:
            raise SystemExit('audio sine table differs from offline authoring')
        print('ok: original Q31 quarter-sine table matches offline authoring')
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected)
