#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Author physiological illustration tables offline; --check verifies exact generated bytes."""
import argparse
import hashlib
import json
from fractions import Fraction
from pathlib import Path
import struct
from spdx_headers import with_header


def sample_shape(shape):
    if 'polynomial_coefficients' in shape:
        coefficients = shape['polynomial_coefficients']
        return [round(sum(Fraction(coefficient) * Fraction(index, shape['length']) ** power
                          for power, coefficient in enumerate(coefficients)) * (1 << 32))
                for index in range(shape['length'])]
    values = []
    for (start, first), (end, last) in zip(shape['landmarks'], shape['landmarks'][1:]):
        for index in range(start, end):
            t = Fraction(index - start, end - start)
            values.append(round((first + (last - first) * (3 * t * t - 2 * t * t * t)) * (1 << 32)))
    if len(values) != shape['length']:
        raise ValueError('landmarks must span the declared table length')
    return values


def electrode_shapes(manifest, reference):
    original = sample_shape(reference['tables']['Qrs'])
    limbs = [[round(Fraction(value * weight, 1000)) for value in original]
             for weight in manifest['limb_qrs_weights_per_1000']]
    phases = [sample_shape({'length': manifest['phase_length'], 'landmarks': manifest['phase_landmarks'][name]})
              for name in ['Early', 'Main', 'Terminal']]
    values = list(limbs)
    for weights in manifest['chest_component_microvolts']:
        values.append([round(Fraction(limbs[0][i] + limbs[1][i] + limbs[3][i], 3) +
                             sum(weight * phase[i] for weight, phase in zip(weights, phases)))
                       for i in range(manifest['phase_length'])])
    shapes = {name: {'values_q32': value} for name, value in zip(
        ['RA', 'LA', 'RL', 'LL', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6'], values)}
    for column, name in enumerate(['PWeightsQ32', 'TWeightsQ32']):
        shapes[name] = {'values_q32': [row[column] * (1 << 32)
                                     for row in manifest['p_t_electrode_weights_per_1000']]}
    return shapes


def render(namespace, class_name, shapes, timing=None):
    lines = ['// Generated by tools/generate_demo_morphology.py; do not edit.',
             '// Project-authored reference illustration; not a validated physiological preset.',
             f'namespace {namespace};', '', f'internal static class {class_name}', '{']
    if timing is not None:
        values = [timing[key] * 1_000_000 for key in ['rr', 'p', 'pr', 'qrs', 'qt', 't']]
        lines.append('    internal static EcgCycleTiming Timing { get; } = new(' + ', '.join(map(str, values)) + ');')
    for name, shape in shapes.items():
        values = shape.get('values_q32')
        if values is None:
            values = sample_shape(shape)
        digest = hashlib.sha256(b''.join(struct.pack('<q', value) for value in values)).hexdigest()
        lines += [f'    // Q32 little-endian table SHA-256: {digest}',
                  f'    internal static IReadOnlyList<long> {name} {{ get; }} = Array.AsReadOnly(new long[]', '    {']
        for offset in range(0, len(values), 4):
            lines.append('        ' + ', '.join(str(value) for value in values[offset:offset + 4]) + ',')
        lines += ['    });']
    lines += ['}', '']
    return '\n'.join(lines)


def arterial_shape(manifest):
    digest = hashlib.sha256(json.dumps(manifest['upstream_vertices'], separators=(',', ':')).encode()).hexdigest()
    if digest != manifest['upstream_vertices_sha256']:
        raise ValueError('upstream pressure vertex evidence changed')
    vertices = [Fraction(value) for value in manifest['upstream_vertices']]
    for index, value in manifest['modified_vertices'].items():
        vertices[int(index)] = Fraction(value)
    values = []
    for sample in range(manifest['length']):
        position = Fraction(sample * (len(vertices) - 1), manifest['length'])
        index = int(position)
        value = vertices[index] + (vertices[index + 1] - vertices[index]) * (position - index)
        values.append(round(value / Fraction(manifest['normalization_peak']) * (1 << 32)))
    return {'Pulse': {'values_q32': values}}


def capnogram_shape(manifest):
    digest = hashlib.sha256(json.dumps(manifest['upstream_vertices'], separators=(',', ':')).encode()).hexdigest()
    if digest != manifest['upstream_vertices_sha256']:
        raise ValueError('upstream CO2 vertex evidence changed')
    v = [Fraction(value) for value in manifest['upstream_vertices']]
    values = [0] * 32
    for vertices, length in [([Fraction(0)] + v[:15], 64), (v[14:213], 384), (v[212:], 32)]:
        for sample in range(length):
            position = Fraction(sample * (len(vertices) - 1), length)
            index = int(position)
            value = vertices[index] + (vertices[index + 1] - vertices[index]) * (position - index)
            values.append(round(value / Fraction('0.7') * (1 << 32)))
    return {'Cycle': {'values_q32': values}}


def cvp_shapes(manifest):
    seeds = manifest['upstream_seeds']
    if hashlib.sha256(json.dumps(seeds, sort_keys=True, separators=(',', ':')).encode()).hexdigest() != manifest['upstream_seeds_sha256']:
        raise ValueError('upstream CVP vertex evidence changed')
    atrial = [Fraction(value) for value in seeds['CVP_Atrioventricular'][:44]]
    first, last = atrial[0], atrial[-1]
    atrial = [max(Fraction(0), value - first - (last - first) * Fraction(index, 43)) for index, value in enumerate(atrial)]
    ventricular = [Fraction(value) for value in seeds['CVP_Ventricular'][36:87]]
    shapes = dict(manifest['project_tables'])
    for name, vertices in [('A', atrial), ('V', ventricular)]:
        peak = max(vertices)
        values = []
        for sample in range(128):
            position = Fraction(sample * (len(vertices) - 1), 128)
            index = int(position)
            value = vertices[index] + (vertices[index + 1] - vertices[index]) * (position - index)
            values.append(round(value / peak * (1 << 32)))
        shapes[name] = {'values_q32': values}
    return shapes


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    manifest = json.loads((root / 'eng/physiology/textbook-ecg-reference.json').read_text())
    chest = json.loads((root / 'eng/physiology/textbook-chest-progression.json').read_text())
    pleth = json.loads((root / 'eng/physiology/pleth-pulse-reference.json').read_text(), parse_float=Fraction)
    arterial = json.loads((root / 'eng/physiology/infirmary-arterial-pulse.json').read_text())
    capnogram = json.loads((root / 'eng/physiology/infirmary-capnogram.json').read_text())
    pulmonary = json.loads((root / 'eng/physiology/infirmary-pulmonary-artery.json').read_text())
    cvp = json.loads((root / 'eng/physiology/infirmary-cvp-components.json').read_text())
    if hashlib.sha256((root / cvp['license_file']).read_bytes()).hexdigest() != cvp['license_sha256']:
        raise ValueError('upstream CVP license evidence changed')
    if hashlib.sha256((root / pulmonary['license_file']).read_bytes()).hexdigest() != pulmonary['license_sha256']:
        raise ValueError('upstream PA license evidence changed')
    if hashlib.sha256((root / capnogram['license_file']).read_bytes()).hexdigest() != capnogram['license_sha256']:
        raise ValueError('upstream CO2 license evidence changed')
    if hashlib.sha256((root / arterial['license_file']).read_bytes()).hexdigest() != arterial['license_sha256']:
        raise ValueError('upstream ABP license evidence changed')
    st = json.loads((root / 'eng/physiology/st-segment-illustration.json').read_text())
    infarction = json.loads((root / 'eng/physiology/infarction-illustration.json').read_text())
    outputs = {
        root / 'src/Monitor.Simulation/Physiology/InfarctionIllustrationTables.cs': render(
            'Monitor.Simulation.Physiology', 'InfarctionIllustrationTables', infarction['tables']),
        root / 'src/Monitor.Simulation/Physiology/StSegmentTables.cs': render(
            'Monitor.Simulation.Physiology', 'StSegmentTables', st['tables']),
        root / 'src/Monitor.Simulation/Physiology/CvpComponentTables.cs':
            '// A/V adapted from Infirmary Integrated CVP seeds, Ibi Keller (Tanjera); C/X/Y/Resp are project-authored.\n'
            '// Apache-2.0; see eng/licenses/infirmary-integrated-LICENSE.md and docs/infirmary-source-notice.md.\n' + render(
                'Monitor.Simulation.Physiology', 'CvpComponentTables', cvp_shapes(cvp)).replace(
                    'Project-authored reference illustration', 'Mixed adapted/project-authored reference illustration'),
        root / 'src/Monitor.Simulation/Physiology/PulmonaryArteryTables.cs':
            '// Adapted from Infirmary Integrated PA_Default, Ibi Keller (Tanjera).\n'
            '// Apache-2.0; see eng/licenses/infirmary-integrated-LICENSE.md and docs/infirmary-source-notice.md.\n' + render(
                'Monitor.Simulation.Physiology', 'PulmonaryArteryTables', arterial_shape(pulmonary)).replace(
                    'Project-authored reference illustration', 'Adapted upstream reference illustration'),
        root / 'src/Monitor.Simulation/Physiology/CapnogramTables.cs':
            '// Adapted from Infirmary Integrated ETCO2_Default, Ibi Keller (Tanjera).\n'
            '// Apache-2.0; see eng/licenses/infirmary-integrated-LICENSE.md and docs/infirmary-source-notice.md.\n' + render(
                'Monitor.Simulation.Physiology', 'CapnogramTables', capnogram_shape(capnogram)).replace(
                    'Project-authored reference illustration', 'Adapted upstream reference illustration'),
        root / 'src/Monitor.Simulation/Physiology/ArterialPulseTables.cs':
            '// Adapted from Infirmary Integrated ABP_Default, Ibi Keller (Tanjera).\n'
            '// Apache-2.0; see eng/licenses/infirmary-integrated-LICENSE.md and docs/infirmary-source-notice.md.\n' + render(
                'Monitor.Simulation.Physiology', 'ArterialPulseTables', arterial_shape(arterial)).replace(
                    'Project-authored reference illustration', 'Adapted upstream reference illustration'),
        root / 'src/Monitor.Simulation/Physiology/PlethPulseTables.cs': render(
            'Monitor.Simulation.Physiology', 'PlethPulseTables', pleth['tables']),
        root / 'src/Monitor.Simulation/Physiology/TextbookElectrodeQrsTables.cs': render(
            'Monitor.Simulation.Physiology', 'TextbookElectrodeQrsTables', electrode_shapes(chest, manifest)),
        root / 'src/Monitor.Simulation/Physiology/TextbookEcgTables.cs': render(
            'Monitor.Simulation.Physiology', 'TextbookEcgTables', manifest['tables'], manifest['timing_ms']),
        root / 'src/Monitor.Simulation/Physiology/RespirationTables.cs': render(
            'Monitor.Simulation.Physiology', 'RespirationTables',
            {'Cycle': {'length': 64, 'landmarks': [[0, 0], [32, 1], [64, 0]]}}),
    }
    for target, expected in outputs.items():
        expected = with_header(target.name, expected.encode()).decode()
        if args.check:
            if target.read_text() != expected:
                raise SystemExit(f'Morphology differs from reproducible output: {target.name}')
        else:
            target.write_text(expected)
    if args.check:
        print('ok: ECG/ST, Resp, Pleth, ABP, CO2, PA and CVP Q32 tables match offline authoring')


if __name__ == '__main__':
    main()
